import { SLOT_COUNT } from "./icons";

// Each pack fills the 24 slots of icons.ts. Slots 0–19 follow LOOKALIKE_SLOT_GROUPS, so every
// pack must put look-alikes at the same positions (0–4, 5–7, 8–11, 12–14, 15–16, 17–19).
// Icons are Microsoft Fluent Emoji 3D images (src/ui/emojiImages.ts); `glyph` is the matching
// Unicode emoji, kept so VoiceOver / TalkBack read the icon's name in the player's language.
export interface PackIcon {
  glyph: string;
  asset: string;
}

export interface IconPack {
  id: string;
  icons: readonly PackIcon[];
  /** How the pack is unlocked: free, bought with coins, a store product, or Pairs+. */
  price: { kind: "free" } | { kind: "coins"; amount: number } | { kind: "iap"; productId: string } | { kind: "plus" };
}

export const ICON_PACKS: readonly IconPack[] = [
  {
    id: "party",
    price: { kind: "free" },
    icons: [
      { glyph: "🥤", asset: "cup_with_straw" },
      { glyph: "🧋", asset: "bubble_tea" },
      { glyph: "🧃", asset: "beverage_box" },
      { glyph: "☕", asset: "hot_beverage" },
      { glyph: "🎉", asset: "party_popper" },
      { glyph: "🍒", asset: "cherries" },
      { glyph: "🍓", asset: "strawberry" },
      { glyph: "🍑", asset: "peach" },
      { glyph: "🍋", asset: "lemon" },
      { glyph: "🍊", asset: "tangerine" },
      { glyph: "🥭", asset: "mango" },
      { glyph: "🍌", asset: "banana" },
      { glyph: "🍏", asset: "green_apple" },
      { glyph: "🍐", asset: "pear" },
      { glyph: "🥝", asset: "kiwi_fruit" },
      { glyph: "🍇", asset: "grapes" },
      { glyph: "🫐", asset: "blueberries" },
      { glyph: "🍫", asset: "chocolate_bar" },
      { glyph: "🍩", asset: "doughnut" },
      { glyph: "🍪", asset: "cookie" },
      { glyph: "🍉", asset: "watermelon" },
      { glyph: "🍍", asset: "pineapple" },
      { glyph: "🥥", asset: "coconut" },
      { glyph: "🧉", asset: "mate" },
    ],
  },
  {
    id: "animals",
    price: { kind: "coins", amount: 1500 },
    icons: [
      { glyph: "🐶", asset: "dog_face" },
      { glyph: "🐺", asset: "wolf" },
      { glyph: "🦊", asset: "fox" },
      { glyph: "🐱", asset: "cat_face" },
      { glyph: "🦁", asset: "lion" },
      { glyph: "🐭", asset: "mouse_face" },
      { glyph: "🐹", asset: "hamster" },
      { glyph: "🐰", asset: "rabbit_face" },
      { glyph: "🐻", asset: "bear" },
      { glyph: "🐼", asset: "panda" },
      { glyph: "🐨", asset: "koala" },
      { glyph: "🐻‍❄️", asset: "polar_bear" },
      { glyph: "🐸", asset: "frog" },
      { glyph: "🐢", asset: "turtle" },
      { glyph: "🦎", asset: "lizard" },
      { glyph: "🐙", asset: "octopus" },
      { glyph: "🦑", asset: "squid" },
      { glyph: "🐔", asset: "chicken" },
      { glyph: "🐤", asset: "baby_chick" },
      { glyph: "🐧", asset: "penguin" },
      { glyph: "🦄", asset: "unicorn" },
      { glyph: "🐝", asset: "honeybee" },
      { glyph: "🦋", asset: "butterfly" },
      { glyph: "🐬", asset: "dolphin" },
    ],
  },
  {
    id: "food",
    price: { kind: "coins", amount: 2000 },
    icons: [
      { glyph: "🍔", asset: "hamburger" },
      { glyph: "🌭", asset: "hot_dog" },
      { glyph: "🥪", asset: "sandwich" },
      { glyph: "🌮", asset: "taco" },
      { glyph: "🌯", asset: "burrito" },
      { glyph: "🍞", asset: "bread" },
      { glyph: "🥐", asset: "croissant" },
      { glyph: "🥖", asset: "baguette_bread" },
      { glyph: "🍕", asset: "pizza" },
      { glyph: "🍟", asset: "french_fries" },
      { glyph: "🍿", asset: "popcorn" },
      { glyph: "🥨", asset: "pretzel" },
      { glyph: "🍣", asset: "sushi" },
      { glyph: "🍱", asset: "bento_box" },
      { glyph: "🥟", asset: "dumpling" },
      { glyph: "🍰", asset: "shortcake" },
      { glyph: "🎂", asset: "birthday_cake" },
      { glyph: "🍦", asset: "soft_ice_cream" },
      { glyph: "🍧", asset: "shaved_ice" },
      { glyph: "🍨", asset: "ice_cream" },
      { glyph: "🧀", asset: "cheese_wedge" },
      { glyph: "🥞", asset: "pancakes" },
      { glyph: "🥓", asset: "bacon" },
      { glyph: "🍳", asset: "cooking" },
    ],
  },
  {
    id: "space",
    price: { kind: "coins", amount: 2500 },
    icons: [
      { glyph: "🌑", asset: "new_moon" },
      { glyph: "🌒", asset: "waxing_crescent_moon" },
      { glyph: "🌓", asset: "first_quarter_moon" },
      { glyph: "🌔", asset: "waxing_gibbous_moon" },
      { glyph: "🌕", asset: "full_moon" },
      { glyph: "⭐", asset: "star" },
      { glyph: "🌟", asset: "glowing_star" },
      { glyph: "✨", asset: "sparkles" },
      { glyph: "🪐", asset: "ringed_planet" },
      { glyph: "🌍", asset: "globe_showing_europe_africa" },
      { glyph: "🌎", asset: "globe_showing_americas" },
      { glyph: "🌏", asset: "globe_showing_asia_australia" },
      { glyph: "☄️", asset: "comet" },
      { glyph: "🌙", asset: "crescent_moon" },
      { glyph: "💫", asset: "dizzy" },
      { glyph: "🚀", asset: "rocket" },
      { glyph: "🛸", asset: "flying_saucer" },
      { glyph: "🌞", asset: "sun_with_face" },
      { glyph: "🌝", asset: "full_moon_face" },
      { glyph: "🌚", asset: "new_moon_face" },
      { glyph: "👽", asset: "alien" },
      { glyph: "🛰️", asset: "satellite" },
      { glyph: "🔭", asset: "telescope" },
      { glyph: "☀️", asset: "sun" },
    ],
  },
  {
    id: "nature",
    price: { kind: "coins", amount: 3000 },
    icons: [
      { glyph: "🌸", asset: "cherry_blossom" },
      { glyph: "🌺", asset: "hibiscus" },
      { glyph: "🌹", asset: "rose" },
      { glyph: "🌷", asset: "tulip" },
      { glyph: "🌼", asset: "blossom" },
      { glyph: "🌲", asset: "evergreen_tree" },
      { glyph: "🌳", asset: "deciduous_tree" },
      { glyph: "🌴", asset: "palm_tree" },
      { glyph: "🍀", asset: "four_leaf_clover" },
      { glyph: "☘️", asset: "shamrock" },
      { glyph: "🌿", asset: "herb" },
      { glyph: "🌱", asset: "seedling" },
      { glyph: "🍁", asset: "maple_leaf" },
      { glyph: "🍂", asset: "fallen_leaf" },
      { glyph: "🍃", asset: "leaf_fluttering_in_wind" },
      { glyph: "🍄", asset: "mushroom" },
      { glyph: "🍄‍🟫", asset: "brown_mushroom" },
      { glyph: "⛅", asset: "sun_behind_cloud" },
      { glyph: "🌤️", asset: "sun_behind_small_cloud" },
      { glyph: "🌥️", asset: "sun_behind_large_cloud" },
      { glyph: "🌈", asset: "rainbow" },
      { glyph: "❄️", asset: "snowflake" },
      { glyph: "🌵", asset: "cactus" },
      { glyph: "🌋", asset: "volcano" },
    ],
  },
  {
    id: "travel",
    price: { kind: "coins", amount: 3500 },
    icons: [
      { glyph: "🚗", asset: "automobile" },
      { glyph: "🚕", asset: "taxi" },
      { glyph: "🚓", asset: "police_car" },
      { glyph: "🚙", asset: "sport_utility_vehicle" },
      { glyph: "🛻", asset: "pickup_truck" },
      { glyph: "🚌", asset: "bus" },
      { glyph: "🚎", asset: "trolleybus" },
      { glyph: "🚐", asset: "minibus" },
      { glyph: "🚂", asset: "locomotive" },
      { glyph: "🚄", asset: "high_speed_train" },
      { glyph: "🚅", asset: "bullet_train" },
      { glyph: "🚊", asset: "tram" },
      { glyph: "✈️", asset: "airplane" },
      { glyph: "🛩️", asset: "small_airplane" },
      { glyph: "🚁", asset: "helicopter" },
      { glyph: "⛵", asset: "sailboat" },
      { glyph: "🚤", asset: "speedboat" },
      { glyph: "🚲", asset: "bicycle" },
      { glyph: "🛵", asset: "motor_scooter" },
      { glyph: "🏍️", asset: "motorcycle" },
      { glyph: "🚢", asset: "ship" },
      { glyph: "🎡", asset: "ferris_wheel" },
      { glyph: "🎢", asset: "roller_coaster" },
      { glyph: "⛽", asset: "fuel_pump" },
    ],
  },
  {
    id: "sports",
    price: { kind: "iap", productId: "faceup_pairs.pack_sports" },
    icons: [
      { glyph: "⚽", asset: "soccer_ball" },
      { glyph: "🏀", asset: "basketball" },
      { glyph: "🏐", asset: "volleyball" },
      { glyph: "🏈", asset: "american_football" },
      { glyph: "🏉", asset: "rugby_football" },
      { glyph: "🎾", asset: "tennis" },
      { glyph: "🥎", asset: "softball" },
      { glyph: "⚾", asset: "baseball" },
      { glyph: "🥇", asset: "1st_place_medal" },
      { glyph: "🥈", asset: "2nd_place_medal" },
      { glyph: "🥉", asset: "3rd_place_medal" },
      { glyph: "🏅", asset: "sports_medal" },
      { glyph: "🏓", asset: "ping_pong" },
      { glyph: "🏸", asset: "badminton" },
      { glyph: "🎳", asset: "bowling" },
      { glyph: "⛳", asset: "flag_in_hole" },
      { glyph: "🏒", asset: "ice_hockey" },
      { glyph: "🥊", asset: "boxing_glove" },
      { glyph: "🥋", asset: "martial_arts_uniform" },
      { glyph: "🥅", asset: "goal_net" },
      { glyph: "🛹", asset: "skateboard" },
      { glyph: "🏆", asset: "trophy" },
      { glyph: "⛸️", asset: "ice_skate" },
      { glyph: "🥏", asset: "flying_disc" },
    ],
  },
  {
    id: "faces",
    price: { kind: "plus" },
    icons: [
      { glyph: "😀", asset: "grinning_face" },
      { glyph: "😃", asset: "grinning_face_with_big_eyes" },
      { glyph: "😄", asset: "grinning_face_with_smiling_eyes" },
      { glyph: "😁", asset: "beaming_face_with_smiling_eyes" },
      { glyph: "😆", asset: "grinning_squinting_face" },
      { glyph: "😉", asset: "winking_face" },
      { glyph: "😊", asset: "smiling_face_with_smiling_eyes" },
      { glyph: "🙂", asset: "slightly_smiling_face" },
      { glyph: "😮", asset: "face_with_open_mouth" },
      { glyph: "😯", asset: "hushed_face" },
      { glyph: "😲", asset: "astonished_face" },
      { glyph: "😳", asset: "flushed_face" },
      { glyph: "😐", asset: "neutral_face" },
      { glyph: "😑", asset: "expressionless_face" },
      { glyph: "😶", asset: "face_without_mouth" },
      { glyph: "😏", asset: "smirking_face" },
      { glyph: "😒", asset: "unamused_face" },
      { glyph: "🥶", asset: "cold_face" },
      { glyph: "🥵", asset: "hot_face" },
      { glyph: "🤢", asset: "nauseated_face" },
      { glyph: "😎", asset: "smiling_face_with_sunglasses" },
      { glyph: "🤓", asset: "nerd_face" },
      { glyph: "🥳", asset: "partying_face" },
      { glyph: "🤠", asset: "cowboy_hat_face" },
    ],
  },
];

export const DEFAULT_PACK_ID = "party";

export function getPack(id: string): IconPack {
  return ICON_PACKS.find((p) => p.id === id) ?? ICON_PACKS[0];
}

const MISSING: PackIcon = { glyph: "?", asset: "prohibited" };

/** Icon for a dealt slot ("0".."23") in the given pack. */
export function iconFor(pack: IconPack, slot: string): PackIcon {
  const index = Number(slot);
  return Number.isInteger(index) && index >= 0 && index < SLOT_COUNT ? pack.icons[index] : MISSING;
}
